#!/usr/bin/env bash

# This function is used to display and log debug messages when writing a script.
#
# Debug messages are only printed if the _DEBUG variable is set to 'true'.

#######################################
# Display and log debug message
#
# ARGUMENTS:
#   $@ - The debug message
#######################################
deb() {
	[[ "${_DEBUG}" == true ]] || return

	local message_type="DEBUG"
	local stylised_message_type
	stylised_message_type=$'\033[4;33;49m'"${message_type}"$'\033[0m' # yellow underline

	local timestamp
	timestamp="$(date +'%Y%m%d%H%M%S')"

	printf "%s\n" "${stylised_message_type}/${_SCRIPT_NAME}: $*" >&2
	printf "%s\n" "${message_type}/${_SCRIPT_NAME} ${timestamp}: $*" >>"${_LOG_FILE}"
}
