#!/usr/bin/env bash

# This function is intended to provide context to errors.
#
# It should be used for all non-fatal errors, and to provide additional context to fatal errors not covered by the exit code.
#
# A fatal error should be one where the script cannot or should not continue. A non-fatal error should be one where
# the script can continue without affecting the core functionality, but where the user should be notified.
#
# Non-fatal errors are tracked by the _ERROR_COUNTER variable, set by script_setup(), to be reported to the user by print_exit_code().

#######################################
# Display and log error message, increment error counter
#
# ARGUMENTS:
#   $@ - The error message
#
# ALTERS:
#   _ERROR_COUNTER, set by script_setup()
#######################################
err() {
	local message_type="ERROR"
	local stylised_message_type
	stylised_message_type=$'\033[4;31;49m'"${message_type}"$'\033[0m' # red underline

	local timestamp
	timestamp="$(date +'%Y%m%d%H%M%S')"

	printf "%s\n" "${stylised_message_type}/${_SCRIPT_NAME}: $*" >&2
	printf "%s\n" "${message_type}/${_SCRIPT_NAME} ${timestamp}: $*" >>"${_LOG_FILE}"

	_ERROR_COUNTER=$((_ERROR_COUNTER + 1))
}
